name: money_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/finance tracker.webp"
  adaptive_icon_background: "#5E3FBE"
  adaptive_icon_foreground: "assets/finance tracker.webp"
  remove_alpha_ios: true
