default_platform(:ios)

def setup_apple_api
  app_store_connect_api_key(
    key_id: "TZW43M7B7J",
    issuer_id: "3195229b-52e7-446a-8d6a-92dedd72fe6a",
    key_filepath: "fastlane/AuthKey_TZW43M7B7J.p8",
    in_house: false
  )
  cert_id = get_certificates(development: false)
  ENV["CERTIFICATE_ID"] = cert_id
end

platform :ios do
  desc "Сборка и заливка только в TestFlight (App Store Connect)"
  lane :testflight do
    setup_apple_api

    get_provisioning_profile(
      app_identifier: "kz.dyace.moneytracker",
      adhoc: false,
      force: true
    )

    build_number = ENV["BUILD_NUMBER"] || "1"
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      xcargs: "CURRENT_PROJECT_VERSION=#{build_number}"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Сборка и заливка только в Firebase App Distribution"
  lane :firebase do
    setup_apple_api

    get_provisioning_profile(
      app_identifier: "kz.dyace.moneytracker",
      adhoc: true,
      force: true
    )

    build_number = ENV["BUILD_NUMBER"] || "1"
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "ad-hoc",
      xcargs: "CURRENT_PROJECT_VERSION=#{build_number}"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      service_credentials_file: "fastlane/firebase-service-account.json",
      groups: "testers"
    )
  end
end
